### ISSUE TITLE
Would it be possible to add a controller?

### ISSUE THREAD

**Issue by Prn-Ice** [atn832/svg_drawing_animation#1]
Hi, thank you for this package, it's amazing and works out of the box. 
Would it be possible in the future to add a controller that will allow for starting/stopping/resetting the animation?

**Comment by atn832** [comment]
It's now supported in the [latest version](https://pub.dev/packages/svg_drawing_animation/changelog#0110). See usage at https://pub.dev/packages/svg_drawing_animation#custom-animation.
